services:
  web-server:
    build: 
      context: .
    restart: unless-stopped
    container_name: php
    ports:
        - "80:80"
        - "5173:5173"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/sites-available/default 
    networks:
      - laravel
    
  database:
    image: mariadb:11.2
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel 

  # redis:
  #   image: 'redis:7.2.3'
  #   container_name: redis
  #   ports:
  #       - '${FORWARD_REDIS_PORT:-6379}:6379'
  #   volumes:
  #       - redis_data:/data
  #   networks:
  #     - laravel

networks:
    laravel:
        driver: bridge

volumes:
  mysql_data:
  redis_data:
