services:
  web:
    build: 
      context: .
    restart: unless-stopped
    container_name: php
    ports:
        - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/sites-available/default
      - ./docker/php/supervisor/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
      - ./docker/php/uploads.ini:/etc/php/8.2/fpm/conf.d/uploads.ini
    networks:
      - laravel
    
  db:
    image: mariadb:11.2
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel 
  node:
    image: node:alpine3.19
    working_dir: /var/www/html
    command: "npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html
    networks:
      - laravel 
  # redis:
  #   image: 'redis:7.2.3'
  #   container_name: redis
  #   ports:
  #       - '${FORWARD_REDIS_PORT:-6379}:6379'
  #   volumes:
  #       - redis_data:/data
  #   networks:
  #     - laravel

networks:
    laravel:
        driver: bridge

volumes:
  mysql_data:
  redis_data:
