services:
  web:
    build: 
      context: .
    restart: unless-stopped
    container_name: web
    command: "npm run dev -- --host"
    ports:
        - "80:80"
        - "5173:5173"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/sites-available/default
      - ./docker/php/supervisor/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
      - ./docker/php/uploads.ini:/etc/php/8.2/fpm/conf.d/uploads.ini
    networks:
      - laravel
    
  db:
    image: mariadb:11.2
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel 
networks:
    laravel:
        driver: bridge

volumes:
  mysql_data:
  redis_data:
