services:
  php:
    build: 
      context: .
    restart: unless-stopped
    container_name: php
    volumes:
      - ./:/var/www/html

    networks:
      - laravel
      
  web:
    image: nginx:1.24.0-alpine3.17
    restart: unless-stopped
    container_name: nginx
    working_dir: /var/www/html
    volumes:
      -  ./:/var/www/html
      - ./docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
    ports:
       - '${APP_PORT:-80}:80'
    networks:
      - laravel
    
    
  database:
    image: mariadb:11.2
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel 

  node:
    image: node:21.5.0-alpine3.19
    working_dir: /assets
    volumes:
      - ./:/assets
    ports:
      - "5173:5173"
    networks:
      - laravel
    command: npm run dev -- --host


  # redis:
  #   image: 'redis:7.2.3'
  #   container_name: redis
  #   ports:
  #       - '${FORWARD_REDIS_PORT:-6379}:6379'
  #   volumes:
  #       - redis_data:/data
  #   networks:
  #     - laravel

networks:
    laravel:
        driver: bridge

volumes:
  mysql_data:
  redis_data:
